apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: backup-monitor
data:
  config.yml: |
    tunnel: 84a6781d-805a-40d7-ab67-06c4c12be547
    credentials-file: /etc/cloudflared/credentials.json
    no-autoupdate: true
    ingress:
      - hostname: backup-monitor.gr
        service: http://telemetry-api.backup-monitor.svc:8000
      - hostname: www.backup-monitor.gr
        service: http://telemetry-api.backup-monitor.svc:8000
      - service: http_status:404
